### PR TITLE
time_genbranch: Add tool

### PR DESCRIPTION
**Pull request by guludo**
Tool for measuring execution time of genbranch operations. Useful for analyzing possible improvements in execution time.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Wouldn't it be better as an option to genbranch rather than a separate tool?

**Comment by lucasdemarchi** [comment]
or even an env var if we want to hide it from options normally used by users rather than git-pile developers

**Comment by guludo** [comment]
> Wouldn't it be better as an option to genbranch rather than a separate tool?

Considering that `git pile genbranch` is for a single run and that the proposed tool does `2 * (n + 1)` genbranch runs and aggregate the result, maybe better yet to define it as a hidden command? I'm thinking `git pile time-genbranch`

**Comment by lucasdemarchi** [comment]
ok... but I'm not sure we want to expose this as a command like the others. This seems more an "internal tool" than something someone would be running every day

**Comment by guludo** [comment]
Yep, hence the "hidden command" :-)
Maybe we could have those kind of commands enabled with env var `GIT_PILE_DEV`.

**Review by lucasdemarchi — APPROVED** [review]

**Pull request merged**
