### PR TITLE
genbranch: enable split index

### PR DESCRIPTION
**Pull request by lucasdemarchi**
As found out by Matt Roper <matthew.d.roper@intel.com>, we can improve
a lot the time taken by git pile genbranch by using the core.splitIndex
if we are using a big repo like the Linux kernel.

Initially we enabled this in the repo as a configuration, however
leaving it enabled creates some problems during rebase operations:
git leaves behind the .git/sharedindex.* files.

So, instead of enabling this per repository, let's enable it only during
the git-am operation inside the genbranch command.

With this change a genbranch in a large repository like the Linux kernel
and around 2200 commits take ~30s instead of 180s, so we have a ~6x
performance improvement.

Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@mattrope ping

**Review by ashutoshx — APPROVED** [review]
There are no other undesirable side effects of doing this, correct?

**Review by mattrope — APPROVED** [review]

**Comment by mattrope** [comment]
> There are no other undesirable side effects of doing this, correct?

No side effects for doing this on the 'git am' operations used by genbranch.  There does seem to be a bug with split index when performing rebases (it leaves behind a bunch of shared index files rather than properly re-using the same one.  I've reported that on the git mailing list:  https://public-inbox.org/git/20210916055057.GT3389343@mdroper-desk1.amr.corp.intel.com/T/#u

**Comment by lucasdemarchi** [comment]
I enabled it yesterday in git-pile and left genlinear-branch running overnight on ~2000 refs. This morning I gave the repo some light use with other operations and didn't notice any problems. I will keep running with this change a little more before merging.

**Comment by lucasdemarchi** [comment]
This is not really working as git keeps switching split-index mode on and off while applying the patches. This makes it create one sharedindex file per commit, which slows us down. Until we figure out a solution, the speedup can be obtained by wrapping the entire genbranch with the config changes:

```
git config core.splitIndex true; git pile genbranch -i; git config core.splitIndex false
```

Leaving it enabled will create the same problems when doing a rebase.

**Comment by mattrope** [comment]
Maybe rather than updating the config, we should just directly turn split index mode on/off in genbranch (but still honor any explicit configuration that the user is already using).  In pseudocode:

```
if git config --get core.splitindex != false
   git update-index --split-index

...invoke git am...

if git config --get core.splitindex != true
   git update-index --no-split-index
```

**Comment by lucasdemarchi** [comment]
I will give that a try... I enabled it in CI by setting the config, I will switch it to set the value in the index only. Thanks.

**Comment by lucasdemarchi** [comment]
Pushed new version using `git update-index --[no-]split-index` around the call to git am. Tested this with genbranch and checking if we would still have problems on rebase. Remaining problem is that it will create 1 .git/sharedindex.* file per genbranch. The default value for splitIndex.sharedIndexExpire is 2 weeks which may be too much if this is enabled like this in git-pile.  Maybe also wrap a call to forcefully expire the shared index?

**Pull request merged**
